---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine

inputs:
  - name: repo

outputs:
  - name: output

run:
  path: sh
  args:
  - -exc
  - |
    cp repo/data.txt output/
    echo 1 >> output/data.txt
