resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 15s
    source:
      repository: kharandziuk/concourse-training
      access_token: ((github-access-token))

jobs:
  - name: run-tests
    plan:
    - get: pull-request
      trigger: true
      version: every
    - put: pull-request
      params:
        path: pull-request
        status: pending
        context: test
    - task: unit-test
      privileged: true
      file: pull-request/ci/tasks/test.yml
      on_failure:
         put: pull-request
         params:
           path: pull-request
           status: failure
           context: test
    - put: pull-request
      params:
        path: pull-request
        status: success
        context: test

  - name: run-flake8
    plan:
    - get: pull-request
      trigger: true
      version: every
    - put: pull-request
      params:
        path: pull-request
        status: pending
        context: lint
    - task: unit-test
      privileged: true
      file: pull-request/ci/tasks/flake8.yml
      on_failure:
         put: pull-request
         params:
           path: pull-request
           status: failure
           context: lint
    - put: pull-request
      params:
        path: pull-request
        status: success
        context: lint
